---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
node_js:
  - "stable"
  - "7.1.0"
  - "7.0.0"
  - "6.9.1"
  - "6.5"
  - "6.4"
  - "6.3"
  - "5.12"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
install:
  - npm install
  - npm install jscoverage coveralls
after_script:
  - npm run coveralls
