---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
node_js:
  - "stable"
  - "10.15"
  - "9.11"
  - "8.15"
  - "7.1"
  - "6.9"
  - "6.3"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
after_script:
  - npm run coveralls
