---
language: node_js
sudo: false
node_js:
  - "stable"
  - "10.15"
  - "9.11"
  - "8.15"
  - "7.1"
  - "6.9"
  - "6.3"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
after_script:
  - npm run coveralls
